Add GitHub actions
prebid/prebid-cache-java pull request #60
Opened 2022-04-20 12:35 UTC by marki1an

2022-04-26 12:49 UTC, And1sS approved these changes

2022-04-27 08:08 UTC, And1sS requested changes

2022-04-27 08:08 UTC, And1sS commented on .github/workflows/pr-java-ci.yml
> +        run: mvn -B package --file extra/pom.xml
Pls, remove invalid `extra/`

2022-05-04 05:06 UTC, SerhiiNahornyi approved these changes

2022-05-04 05:07 UTC, merged